# Generated by Django 5.2.8 on 2025-11-27 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarketingEventLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('event_name', models.CharField(max_length=255)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('response', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(default='pending', max_length=64)),
                ('attempts', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MarketingIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('facebook_pixel', 'Facebook Pixel'), ('facebook_capi', 'Facebook Conversion API'), ('gtm', 'Google Tag Manager'), ('ga4', 'Google Analytics 4')], max_length=64)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(default='inactive', max_length=32)),
                ('last_tested_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
