# Generated by Django 5.2.8 on 2025-11-28 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_type', models.CharField(blank=True, choices=[('smtp', 'Smtp'), ('api', 'Api')], default='smtp', max_length=25, null=True)),
                ('mail_type', models.CharField(blank=True, choices=[('info', 'Info'), ('no_reply', 'No Reply'), ('contact', 'Contact'), ('career', 'Career')], default='info', max_length=25, null=True)),
                ('server', models.CharField(blank=True, max_length=50, null=True)),
                ('host_user', models.CharField(blank=True, max_length=255, null=True)),
                ('host_password', models.CharField(blank=True, max_length=255, null=True)),
                ('host', models.CharField(blank=True, max_length=255, null=True)),
                ('port', models.CharField(blank=True, max_length=10, null=True)),
                ('tls', models.BooleanField(default=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('reply_to', models.EmailField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('api_key', models.CharField(blank=True, max_length=500, null=True)),
                ('ssl', models.BooleanField(default=False)),
                ('is_default', models.BooleanField(default=False)),
                ('today_count', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('daily_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('today_date', models.DateField(blank=True, null=True)),
                ('today_complete', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='marketingeventlog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
