# Generated by Django 5.2.8 on 2025-11-29 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_emailconfig_alter_marketingeventlog_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailconfig',
            name='is_default',
        ),
    ]
