# Generated by Django 6.0 on 2026-01-12 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0003_remove_emailconfig_is_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketingintegration',
            name='provider',
            field=models.CharField(choices=[('facebook_pixel', 'Facebook Pixel'), ('facebook_capi', 'Facebook Capi'), ('gtm', 'Gtm'), ('ga4', 'Ga4')], max_length=64),
        ),
        migrations.AlterField(
            model_name='marketingintegration',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=32),
        ),
    ]
