# Generated by Django 5.2.8 on 2025-11-28 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_customuser_phone_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerprofile',
            old_name='uuid',
            new_name='profile_uuid',
        ),
    ]
