# Generated by Django 5.2.8 on 2025-11-28 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_uuid_customerprofile_profile_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('area', models.CharField(blank=True, max_length=50, null=True)),
                ('upazila', models.CharField(blank=True, max_length=50, null=True)),
                ('district', models.CharField(max_length=50)),
                ('country', models.CharField(default='Bangladesh', max_length=50)),
                ('post_code', models.CharField(blank=True, max_length=10, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='accounts.customerprofile')),
            ],
        ),
    ]
