# Generated by Django 6.0 on 2026-02-06 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customeraddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
    ]
