# Generated by Django 5.2.8 on 2025-11-27 01:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0006_remove_productvideo_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageLandingPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_details_section_title', models.CharField(blank=True, max_length=255, null=True)),
                ('product_variation_section_title', models.CharField(blank=True, max_length=255, null=True)),
                ('why_buyolex_section_title', models.CharField(blank=True, max_length=255, null=True)),
                ('review_section_title', models.CharField(blank=True, max_length=255, null=True)),
                ('policy_section_title', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('product', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.product')),
            ],
        ),
    ]
