# Generated by Django 5.2.8 on 2025-11-27 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagelandingpage',
            name='hero_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=20),
        ),
    ]
