# Generated by Django 6.0 on 2026-04-22 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_pages', '0002_homepagelandingpage_hero_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagelandingpage',
            name='code',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
