# Generated by Django 5.2.8 on 2025-11-27 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_productvariant_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvideo',
            name='variant',
        ),
    ]
