# Generated by Django 5.2.8 on 2025-11-27 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_remove_productvideo_variant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvideo',
            name='role',
        ),
    ]
