# Generated by Django 5.2.8 on 2025-11-29 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_order_user_remove_review_user_order_customer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='discount_amount',
            new_name='c_unit_price',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='subtotal',
            new_name='d_unit_price',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='unit_price',
            new_name='discount_total_price',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
