# Generated by Django 5.2.8 on 2025-11-29 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_rename_discount_amount_orderitem_c_unit_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='discount_total',
        ),
        migrations.RemoveField(
            model_name='order',
            name='grand_total',
        ),
    ]
