# Generated by Django 5.2.8 on 2025-11-29 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_remove_order_discount_total_remove_order_grand_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='items_total',
        ),
    ]
