# Generated by Django 6.0 on 2025-12-07 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_delivery_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_type',
            field=models.CharField(choices=[('cod', 'Cod'), ('online_payment', 'Online Payment'), ('delivery', 'Delivery'), ('pickup', 'Pickup')], default='cod', max_length=50),
        ),
    ]
