# Generated by Django 6.0 on 2026-01-15 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_order_delivery_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_type',
            field=models.CharField(choices=[('COD', 'Cod'), ('online_payment', 'Online Payment'), ('delivery', 'Delivery'), ('pickup', 'Pickup')], default='COD', max_length=50),
        ),
    ]
