# Generated by Django 6.0 on 2026-02-09 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_alter_order_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogisticServiceProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logistic_code', models.CharField(blank=True, max_length=4, null=True)),
                ('name', models.CharField(choices=[('PATHAO', 'Pathao'), ('REDX', 'Redx'), ('STEADFAST', 'Steadfast')], max_length=25)),
                ('account', models.CharField(max_length=25)),
                ('base_url', models.URLField(max_length=255)),
                ('api_key', models.CharField(max_length=255)),
                ('secret_key', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
