# Generated by Django 6.0 on 2026-02-09 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_logisticserviceprovider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('new', 'New'), ('Follow Up', 'Follow Up'), ('confirmed', 'Confirmed'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('returned', 'Returned'), ('refunded', 'Refunded')], default='new', max_length=50),
        ),
    ]
