# Generated by Django 6.0 on 2026-04-21 23:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_order_note_order_work_assign'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shipment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
