# Generated by Django 6.0 on 2026-04-21 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_shipment_created_at_shipment_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='courier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments', to='orders.deliveryoption'),
        ),
    ]
