# Generated by Django 5.2.8 on 2025-11-27 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryReturnPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('header', models.TextField(blank=True, null=True)),
                ('content', models.JSONField(blank=True, default=list)),
                ('footer', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='My Marketplace', max_length=255)),
                ('site_slogan', models.CharField(blank=True, max_length=255, null=True)),
                ('primary_logo', models.ImageField(blank=True, null=True, upload_to='logo/')),
                ('secondary_logo', models.ImageField(blank=True, null=True, upload_to='logo/')),
                ('intro_video', models.FileField(blank=True, null=True, upload_to='intro-videos/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='logo/')),
                ('primary_color', models.CharField(blank=True, max_length=20, null=True)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('timezone', models.CharField(default='UTC', max_length=64)),
                ('payment_gateways', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WhyBuyolex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(blank=True, max_length=255, null=True)),
                ('header', models.TextField(blank=True, null=True)),
                ('content', models.JSONField(blank=True, default=list)),
                ('footer', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
