# Generated by Django 5.2.8 on 2025-11-27 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0002_homepagelandingpage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HomePageLandingPage',
        ),
    ]
